### ISSUE TITLE
Trees, ores, caves, lava

### ISSUE THREAD

**Issue by MostAwesomeDude** [bravoserver/bravo#10]
These all need to be implemented.

**Comment by Varriount** [comment]
As a note, here's a link that might work for caves. I can see converting it to 3d easily. http://properundead.com/2009/03/cave-generator.html

**Comment by MostAwesomeDude** [comment]
Ores are done but slow. That entire section of generator will need to be sped up.

**Comment by MostAwesomeDude** [comment]
Splitting into new issues and closing this one. Update your bookmarks.
