### ISSUE TITLE
Lighting Issues - Suggestions

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#100]
Have the server do lighting when generating, like a generator. This way chunks generated at night look like they are night
Have the server actually save lighting
Have the server accept the client's lighting updates... It doesn't appear to do this currently, from the way lighting updates are lost when a chunk is unloaded

If we could get a explanation on how the server does lighting, we could put forth more suggestions. Currently it appears that the server starts analyzing chunks at random points

**Comment by MostAwesomeDude** [comment]
I explained on IRC why your list of suggestions are all based on invalid assumptions.

Lighting used to be based on a lookup table of glowing blocks, but it got changed a few patches back and I don't really want to touch it again. Lighting is hard!
