### ISSUE TITLE
Web services and interfaces

### ISSUE THREAD

**Issue by barsch** [bravoserver/bravo#107]
A lot of configuration stuff could be done in parallel to the command line within a web based administration interface. I suggest a new service (HTTPS) and proper interfaces to write plug-ins for this. HTTPS requires a few more Python dependencies which are maybe not wanted - so a standard HTTP service would be fine too - could be proxied by a "real" web server such as Apache.

Another service could focus on public content such as generating realtime statistics from the running Bravo server or a terrain map with the actual player position etc. Again interfaces for such plug-ins must be defined beforehand.

Both services would enhance the user accessibility and experience with Bravo.

**Comment by MostAwesomeDude** [comment]
Twisted Web is highly superior to Apache for what we're going to be doing. Things like SSL are "free" that way.

Yes, I agree. It is a long-term goal (say, a week or two) to have configuration and services be (a) fully dynamic and (b) isolated per-service, to provide a more flexible and accessible system.

**Comment by MostAwesomeDude** [comment]
Done, to the extent that it will be done. There will _not_ be any way to configure the server through this interface, though, unless somebody can suggest a relatively bullet-proof way to do it.
