### ISSUE TITLE
Lightmaps still regenerate client-side

### ISSUE THREAD

**Issue by MostAwesomeDude** [bravoserver/bravo#11]
Wonder if this is a client bug or not, but our lightmaps suck and the client appears to be aware of this.

**Comment by Varriount** [comment]
I think that the server might be sending partial or improperly calculated lightmaps, eg, The map may be an entire brightness level off, and this is causing the client to recalculate the entire map. If someone gets a proxy working, we might be able to find what differences are in the lightinhg packets for Beta and Vanilla

**Comment by MostAwesomeDude** [comment]
Fixed. There's also code and lookup tables for block lighting, once we start dealing with block lights.
