### ISSUE TITLE
"Couldn't select in chunk (-1, -1)" in Client

### ISSUE THREAD

**Issue by barsch** [bravoserver/bravo#113]
Reproducable bug on my machine without output to server but client quits and shows the message above
1. start a new world (i tested it with custom and default ini for hooks and generators)
2. get a block for the inventory (e.g. dig a dirt block or whatever)
3. run in direction of sun
4. point the cross always at the horizont
5. keep clicking the right button
6. at a certain point client crashes (I guess a chunk border or so ...)

nasty ...

**Comment by Varriount** [comment]
Clients send the chunk coordinate -1 -1 -1 when placing blocks in air, or when "placing" items, like a stick. Since there is no -1 -1 -1 y value (the world is only 1 chunk thick) the server chokes on this and sends a error to the client. I don't know why this crashes the client however.

**Comment by MostAwesomeDude** [comment]
The server doesn't choke at all. This is a safety measure, and kicks in as soon as the client no longer has chunk (-1, -1) loaded. We don't let people build, dig, select, or anything else, in chunks which they don't have loaded; it's indicative of overzealous bot behavior and requires us to load chunks far too often.

That said, I had thought we were covered for all of these cases. I'll see if I can reproduce and add the proper armor for this.

**Comment by Varriount** [comment]
Er, from what I have heard from people on #mcdevs, the client sends -1 -1 -1 when placing blocks in "air" or when "placing" items, such as a stick

**Comment by MostAwesomeDude** [comment]
4cd39419889423ddd2b74a0f05d7f01214ef6b4f fixes this.

**Comment by justinnoah** [comment]
Something has unfixed this.
