### ISSUE TITLE
Building to "fast" crashes client

### ISSUE THREAD

**Issue by barsch** [bravoserver/bravo#114]
If I build to fast it crashes without any error message in server log.

**Comment by Varriount** [comment]
This is because the mechanism which is supposed to prevent bots or hacks from building too fast is set too high, causing normal clients to trigger it. The error isn't actually an error, the server sends the client a error message, but it seems the client is choking on it.

**Comment by MostAwesomeDude** [comment]
Hm. What crashes? Is there a traceback?

**Comment by barsch** [comment]
no traceback on server side - client just disconnects with "Internal exception: java.net.SocketException: Connection reset"

**Comment by MostAwesomeDude** [comment]
The limit's been raised to 0.2, or 5 digs/s. Can clients really go that fast?

**Comment by barsch** [comment]
same result as before :/

i just take some block via give - keep the right button pushed and walk backwards - after a few blocks client disconnects

**Comment by barsch** [comment]
ok i manually played with line 539 in bravo/protocols/beta.py and if I set the check self.last_dig_build_timer < 0.1 it seems to work for my machine

**Comment by barsch** [comment]
actually it still crashes - but now I got the message you are building to fast

if i comment out line 539-540 it runs stable ..

edit: using <0.9 I couldn't manage to crash the client anymore - now my finger burns from clicking ^^

**Comment by Varriount** [comment]
Players can't dig that fast, but they can place blocks that fast.

**Comment by MostAwesomeDude** [comment]
88648213bb2669249b9898a7534ef0f6132d84ab should fix this. If that's still not enough, lemme know.

**Comment by barsch** [comment]
works like a charm
