### ISSUE TITLE
Alternate world teleportation/Nether Travel

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#117]
I know that bravo has multiworld functionality, But players need a way to switch from one world to another, so we could have something like one world being the nether, and the other being the overworld, and players being able to switch between the two.

**Comment by MostAwesomeDude** [comment]
Once this functionality shows up in the wire protocol, we'll start adding support for it. However, at this time, there's no way to do this for a client. I'll add in some of the dimension stuff anyway.

**Comment by Varriount** [comment]
Er, there is a way for this to be done, I've seen it and done it in Bukkit...
http://forums.bukkit.org/threads/fun-nethergate-v0-42-just-like-single-player-357.3430/

**Comment by MostAwesomeDude** [comment]
Read that thread more carefully, please; that thread is for chunk hax and doesn't actually change the dimension. The client can't be respawned in a new dimension AFAICT.

Remember that the dimension is a property of the world. Switching between worlds would not be a problem as long as the two worlds are of the same dimension.

**Comment by MostAwesomeDude** [comment]
48c146aace0dc855837f3955d532d4589f815519 provides the metadata alluded to in my first reply, and additionally makes grass tints happen on the client again.
