### ISSUE TITLE
Alternative serializing backends

### ISSUE THREAD

**Issue by barsch** [bravoserver/bravo#118]
I would like to see support for alternative backends such as a relational database (SQLite, Postgres, etc.) or other database approaches (e.g. CouchDB, Tokyo Cabinet, ZopeDB) in order to reduce disk I/O operations (==time) due to the large amount of files used by the default serializers.

The current serializing system is purely file based essentially mapping a single chunk to a single file. The "one file per chunk mechanic" is also partly hard-coded in the serialize.py file. This mechanic should be IMHO moved to the serializers itself (or by introducing a subclass for file based serializers) eventually opening the road to alternative approaches.

Related articles:
- http://www.haxney.org/2011/02/minecabinet-database-backed-chunk.html 
- http://www.minecraftforum.net/viewtopic.php?f=25&t=120160

**Comment by MostAwesomeDude** [comment]
I don't care about databases, but this has to happen anyway for the Beta 1.3 file format, which stashes multiple chunks per file. Also, the current system is not very pluggable or tractable. Some kind of World composition would work better.

**Comment by MostAwesomeDude** [comment]
Whew, all done. Check the comment log; the past two days' commits are nearly all geared towards solving this bug. In addition, the new MCR format is supported.
