### ISSUE TITLE
Snow overrides non-air blocks.

### ISSUE THREAD

**Issue by actown** [bravoserver/bravo#13]
While loading a map, beta will sometimes replace non-air blocks with snow.

**Comment by MostAwesomeDude** [comment]
Marking as important; we should _never_ be doing this.

**Comment by MostAwesomeDude** [comment]
2fc2671dacaf0d52d7e8733e91b848a6b4b07c48 rewrites the winter season to very specifically only place snow where air was before, and to be more respectful of snow-resistant blocks. The end result should hopefully be satisfactory.
