### ISSUE TITLE
Loading world for first time

### ISSUE THREAD

**Issue by mattbasta** [bravoserver/bravo#136]
I copied a world that was generated by the latest version of the vanilla MC server for use with Bravo. Upon logging in, a few things I noticed:
- No trees or plants
- Everything is covered in snow/water is ice

A few other things to note: lighting was preserved (tree shadows were still present), but it was quickly replaced and overwritten with the default lighting.

Don't even begin to know where to start debugging this. Any ideas?

**Comment by Varriount** [comment]
The snow ice bug isn't actually a bug. Bravo has seasons, and the season which it starts with is winter. Of course, winter means snow. About the plants issue, I'm not sure, sounds odd. Did the original map retain it's foliage, or was it the generated bits that had none?
Lighting for bravo, as has been said many times before, is off. Not a single pure custom server has lighting exactly right. MostAwesomeDude and TKTech, both people more experienced than I, plan to get together and sort lighting out. 
If you want to know where to begin debugging and fixing easier bugs, try implementing what I suggested at https://github.com/MostAwesomeDude/bravo/issues/#issue/135
Add if statements and checks to the build plugin to prevent players from placing blocks on themselves (For player coordinate examples, look in warps.py) and an if statement that checks to see if the block being replaced is air. Putting these checks before the code that removes a block from inventory should correct that third bugs as well, I think.

**Comment by mattbasta** [comment]
If the seasons aren't a bug, then it's probably wise to at least note that they will happen automatically in the README. It would probably also (if it hasn't been done already; I don't see it in bravo.ini.example) be a good idea to make them an optional setting. I tried removing all of the references to snow from the ini, but even with a clean-generated world, it's still winter time. I can try my hand at hacking something together if there's no objection.

Shame there's no lighting, but I suppose my complaint only applies for existing worlds. I wouldn't have noticed the lighting issues if there weren't phantom shadows everywhere. A clean-generated world has no such issue(s). Frankly, shadows are the least of my concerns.

Anyway, I rebuilt the world by deleting the old directory that I was using, but everything is still an icy tundra. Hills, plateaus, iced over lakes and ponds, but not a single tree, mushroom, etc. etc. etc. Any idea what could be causing these from being generated/rendered?

**Comment by Varriount** [comment]
There are no flower generators, nor is there a tree generator. Look in generators.py for all the generators we have. Bravo does have lighting, it's just not 100% the way notch does it, and is quite buggy. Lighting is hard, especially when you have to guess the rules.

**Comment by mattbasta** [comment]
Ok, at least I'm not completely broken.

Shouldn't a lack of trees be a much more severe bug? You can't actually get started with a game without trees.

**Comment by Varriount** [comment]
It's not a bug unless its been implemented. I believe MostAwesomeDude has a somewhat buggy tree generator, but he hasn't commited it yet. I might be able to give you a quick and dirty implementation of trees, but they would look all the same.

**Comment by mythmon** [comment]
Also, I don't feel that Bravo is ready yet to "get started with a game". It is more like creative mode at this point. You will also note the lack of mobs and the inability to see other players.

**Comment by mattbasta** [comment]
Ah, I suppose it depends on your definition and interpretation of a bug.

**Comment by mattbasta** [comment]
Does anybody know where the (buggy) tree generator is? Maybe I can take a whack at it.
