### ISSUE TITLE
Block Placement, Night Time, Pickup, and Serializers.

### ISSUE THREAD

**Issue by dbdii407** [bravoserver/bravo#137]
I wasn't able to get bravo server end to launch at first due to a problem with plugins/serializers.py line 94. What goes in the config exactly so that it launches without my modification?

Night time is also messed up. The sky will change dark but the land will not. There is also some random shadow error that appears when placing a block down. Some items I cannot pick up after throwing them on the ground (diamond, sticks, torches, etc...) and there is also an issue where if I place a block outside of the mountains, the block will float up one from where I placed it.

Hope I can get some knowledge on these issues! :)

**Comment by Varriount** [comment]
You aren't being specific enough. Lighting is buggy, and we are still fixing it. Please red the other tickets. 

What exact items can you not pick up? How did you place them on the ground? Were they crafted, or spawned with /give? What do you mean be "outside of the mountains"?

Your serializers problem means that something is wrong with your world folder, or that you are using the wrong serializer to read the world. Is your 
world newly generated, or was it generated by a vanilla server? What format is it, the old .dat format or the mclevel format?

**Comment by dbdii407** [comment]
"What exact items can you not pick up?" diamond, sticks, torches, etc...
"How did you place them on the ground?" Tried to craft a diamond pickaxe, but it wouldn't let me, so I exited out of crafting and they fell on the ground. Placed torches also do this when you try to take them off the wall.
"Were they crafted, or spawned with /give?" Give
"What do you mean be "outside of the mountains"" When you dig inside of a mountain. There's now an inside and outside of the mountain.

As for the serializer problem, I tried to find documentation on it but I couldn't find anything. I don't understand it.
