### ISSUE TITLE
Trees

### ISSUE THREAD

**Issue by MostAwesomeDude** [bravoserver/bravo#140]

**Comment by squiddy** [comment]
I remember you saying that you already worked on this, any way one could have a look at the current status?

**Comment by MostAwesomeDude** [comment]
A sapling generator has been merged; the next step is to clean up and merge the chunk of code that turns saplings into trees.

**Comment by MostAwesomeDude** [comment]
A handful of tree generators based on Forester have been merged. Now, the final step: To get the trees to actually grow. This is the tricky part, and it'll require a bit of thought.

**Comment by MostAwesomeDude** [comment]
Well, #143 is closed: Automatons are now possible.

**Comment by MostAwesomeDude** [comment]
All finished here.
