### ISSUE TITLE
Automatons (Grass, trees, etc.)

### ISSUE THREAD

**Issue by MostAwesomeDude** [bravoserver/bravo#143]
Anything which:
- Expects to be handed a list of coordinates for blocks it cares about
- Periodically wakes up as long as it has a list, touches some or all of its blocks, then sleeps again
- Will, given enough time, discard coordinates from its list as it stops caring about them

These are things that will eventually reach equilibrium. Saplings, water, lava. There are a couple special cases, like dirt to grass, and redstone, where equilibrium won't happen, but I don't think that precludes them from using this interface.

**Comment by Varriount** [comment]
How would this go about with the current hooks? Grass growth isn't immediate.. Perhaps some sort of looping call back that does grass growth in a chunk?

**Comment by MostAwesomeDude** [comment]
Yeah, all of these automatons would have some sort of time interval attached, which would be wired to a LoopingCall. I've anticipated some sort of new plugin which would automatically get to specify a list of built and dug blocks which it cares about, and then would have its list of concerned blocks automatically updated.

**Comment by MostAwesomeDude** [comment]
Updating the bug information.

**Comment by MostAwesomeDude** [comment]
Work has happened for this one. We now have an IAutomaton interface, and water and lava are using it instead of their build hooks. I think I'm going to close this bug now, and open up another bug for anything we want to definitely get into 1.5, like grass and trees.
