### ISSUE TITLE
Connected player can't see other player until they move

### ISSUE THREAD

**Issue by squiddy** [bravoserver/bravo#146]
Player A joins the game.
Player B joins the game.

A can see B, but not the other way around. When A changes location/orientation, B can see him too. So connected players do get notified about a new player correctly, but it seems that new players can only see existing ones, when a entity-related package was send.

Not sure if this is a client-side bug though, trying to find this out.

**Comment by MostAwesomeDude** [comment]
Does 80d87dc3fe2d40fdce51ee6b06b89b7afa498264 help?

**Comment by MostAwesomeDude** [comment]
protocols/beta: Do position callback earlier.

Hopefully closed by 80d87dc3fe2d40fdce51ee6b06b89b7afa498264?

**Comment by squiddy** [comment]
Unfortunately not, but I'll try this on a official server later today.

It seems the commit introduces a significant delay for the second player before he is spawned and can play, probably caused by the new callback.

**Comment by squiddy** [comment]
This problem does not occur on the official server, so it must be something with the current implementation. I tried to find out how the official server works here, it seems it doesn't send an "Entity" packet (0x1E), but only "Named Entity Spawn" (0x14) followed by a "Entity Relative Move" (0x1F) with zero distance. Changing the code to work like this didn't fix the problem though.
