### ISSUE TITLE
Not handling crouch packet

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#151]
Crouch packets need to be handles, otherwise the server spams messages.

**Comment by MostAwesomeDude** [comment]
What should be done with crouch packets? I can fill out the hook, but I don't want to squelch the message just for the sake of logs.

**Comment by Varriount** [comment]
Add a plugin hook? The speed change the client makes should probably be checked, packet and have a interface for any hooks that want to activate on crouching. Also, the position packets for player entities will need to be modified for states.

**Comment by MostAwesomeDude** [comment]
Packets 18 and 19 (old crouch and new crouch) are both squelched. Is there a good reason to have a single crouch hook? When we can think of a decent animation hook, we can add it.
