### ISSUE TITLE
Classic inventory

### ISSUE THREAD

**Issue by MostAwesomeDude** [bravoserver/bravo#167]
Writing for Ac-town since he's unable to type this.

There should be a Classic-style inventory.

**Comment by tjvr** [comment]
Is this even possible within the Beta protocol?

**Comment by MostAwesomeDude** [comment]
It'll work since the server can control all of the inventory.

Sending from a mobile, pardon my terseness. ~ C.
On Jun 22, 2011 9:50 AM, "blob8108" <
reply@reply.github.com>
wrote:

**Comment by coldelectrons** [comment]
It /should/ work, just like Notch /should/ be a better programmer.

The Notchian method is not strictly server-side.  Both client and server retain state.  The client notifies the server of an inventory action, the server checks its notes, and approves it if everything adds up.  It gets uglier - the crafting is done on both ends, too.  So, technically, it becomes more difficult to use a vanilla client with a non-vanilla server if the server has crafting recipes that the client doesn't know.

I've made some observations on inventory actions, which can be seen on wiki.ng/Protocol 'Talk' page.

**Comment by MostAwesomeDude** [comment]
Closing since Creative mode removes most of the need for a Classic inventory.
