### ISSUE TITLE
Unknown entity Slime, Painting, Music

### ISSUE THREAD

**Issue by Mortal** [bravoserver/bravo#170]
When trying to load an SMP world from the official 1.3 Beta server, I'm getting complaints about Slime and Painting entities.

The following message is about the Painting entity:
    Unknown entity Painting
    Tag for entity:
    TAG_Compound: 13 Entries
    {
       TAG_Byte("Dir"): 0
       TAG_List("Motion"): 3 entries of type TAG_Double
       {
               TAG_Double: 0.0
               TAG_Double: 0.0
               TAG_Double: 0.0
       }
       TAG_Byte("OnGround"): 0
       TAG_Int("TileY"): 69
       TAG_Short("Air"): 300
       TAG_Int("TileX"): 20
       TAG_String("Motive"): Graham
       TAG_Int("TileZ"): -150
       TAG_String("id"): Painting
       TAG_List("Pos"): 3 entries of type TAG_Double
       {
               TAG_Double: 20.5
               TAG_Double: 70.0
               TAG_Double: -150.0625
       }
       TAG_Short("Fire"): 0
       TAG_Float("FallDistance"): 0.0
       TAG_List("Rotation"): 2 entries of type TAG_Float
       {
               TAG_Float: 0.0
               TAG_Float: 0.0
       }
    }

Also, the Slime entity:

```
Unknown entity Slime
Tag for entity:
TAG_Compound: 13 Entries
{
   TAG_List("Motion"): 3 entries of type TAG_Double
   {
           TAG_Double: 1.66083948267e-05
           TAG_Double: -0.0784000015259
           TAG_Double: 0.0
   }
   TAG_Byte("OnGround"): 1
   TAG_Short("HurtTime"): 0
   TAG_Short("Health"): 4
   TAG_Short("Air"): 300
   TAG_String("id"): Slime
   TAG_List("Pos"): 3 entries of type TAG_Double
   {
           TAG_Double: 18.7169352997
           TAG_Double: 10.0
           TAG_Double: -147.399999976
   }
   TAG_Short("AttackTime"): 0
   TAG_Short("Fire"): -1
   TAG_Float("FallDistance"): 0.0
   TAG_List("Rotation"): 2 entries of type TAG_Float
   {
           TAG_Float: 162.113800049
           TAG_Float: 0.0
   }
   TAG_Short("DeathTime"): 0
   TAG_Int("Size"): 1
}
```

And finally, Music just yields the following line:

```
 Unknown tile entity Music
```

**Comment by MostAwesomeDude** [comment]
Hey, two entities I didn't have traces for. Excellent. I'll add these.

I didn't realize that Music was a tile entity. I'll have to investigate getting that one added.

**Comment by squiddy** [comment]
May I point to this particular commit for paintings? It might be of use. https://github.com/squiddy/bravo/commit/f28463126272114cb6e46f9ad4b33e2bc0d46869

**Comment by Mortal** [comment]
@MostAwesomeDude: Feel free to kill the slimes - they're a pain in the butt as it is! I got a lot of messages about slimes and music - if you need, I can provide you with the world I loaded into bravo. The world is a couple months old and we've been 3-4 regulars working in it, so I think it represents real world usage. But maybe you have enough of such worlds already.

@squiddy: That looks cool! I'll try pulling that into my own repo tomorrow.
