### ISSUE TITLE
Can place blocks in armor positions in the inventory

### ISSUE THREAD

**Issue by Wallbraker** [bravoserver/bravo#175]
Seems like the notchian client will send the place commands to the server despite the fact that it thinks it can't place them there.

Step to reproduce:
Mine a dirt block
Open inventory
Grab the dirt block
Try to place dirt block on helmet spot

Actual:
Dirt appears in helmet spot <--- Unexpected (also LOL)
**Notice that that the dirt is still held by the client cursor
Try to place dirt block in a valid inventory location
Dirt block disappears

Expected:
Nothing happens
Try to place dirt block in a valid inventory location
Dirt appears in inventory

**Comment by squiddy** [comment]
Handling of armor slots has some problems. Accepting non-armor items, accepting more than 1 item in a slot, accepting helmet as chestplate for example.

https://github.com/squiddy/bravo/commit/d11e015a6c0bffc6daecc8c1a74d55d1c155fe49 adds some (right now) failing tests that address these, so if/once this gets merged, we can keep track of them.

**Comment by mattbasta** [comment]
I believe this is done because you can use blocks like a pumpkin as a helmet. I'm not aware of how many other "exceptions" there are, but this is definitely intended to some degree.

**Comment by squiddy** [comment]
This bug should be fixed by https://github.com/MostAwesomeDude/bravo/commit/d9b46c4f84cf637ce62e87cec68c9d5e0d4e0650

Armor slots take only one piece of armor and only the appropriate type for each slot. Pumpkin still works as helmet, I added a test that ensures it stays this way some time ago.

**Comment by MostAwesomeDude** [comment]
Yeah, this is definitely fixed. Adding to 1.5's milestone (should have been fixed in 1.4, even!) and closing.
