### ISSUE TITLE
Plugin System - Advancemants, or more fine controls

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#179]
Just from looking at the build hooks, I keep on suspecting that something needs to be done to help fine tune when plugins are called, and what is done with their info.. Example, right now if you want automatically ordered plugins, you have to specify a plugins name, which isn't feasible if you have a plugin system that changes, as plugin makers can't keep track of all other plugins which they need to go before theirs.

Here are a few of my ideas:
Attribute based system:
Plugins could specify attributes, EG, "core" "monitor" etc to specify when they are run, and possibly what is done with their data. Multiple attributes could be available.

Priority System:
Yes, I know that bukkit uses this, but I've seen plenty of other systems besides bukkit use it, from xchat plugins to some of my procedural landscape creation programs. having a set of priorities (Which is similar to the attributes idea) would help specify when plugins are run. there could possibly be sub priorities as well.

In closing, I hope others can come up with ideas that are just as good. The current system is ok, but I don't believe its exact or precise enough. My previous project, icraft, used the same system, and there were complications with plugins all the time. What we need is a system that, while under user can control, can also be finely controlled by the plugin developers.

**Comment by MostAwesomeDude** [comment]
The more I think about it, the more I can see that building itself (the Build plugin) really should be at the top, before anything else. Between automaton interfaces and block orientation data (see #178 for details), it should be possible to eliminate all or nearly all of the "pre-build" build hooks, leaving only post-build. The Build plugin could then be brought back into the core, roughly, and be entirely guarded by a true security interface. Then plugins wouldn't have to do silly things like the cancellable pipeline.

**Comment by MostAwesomeDude** [comment]
We did the interesting parts of this, like bringing the build plugin back into the core. I think that further improvements need to be per-plugin or on the plugin loader.
