### ISSUE TITLE
light

### ISSUE THREAD

**Issue by alucas** [bravoserver/bravo#183]
As you can see, the skylight is not good:
http://img709.imageshack.us/img709/7040/20110402200656.png

Some blocks like "leaves" must be transparent, but in the function "regenerate_skylight" in "chunk.py" l.195:

lightable = logical_not(self.blocks)

So only "Air" blocks are transparent. I fix this in this commit:
https://github.com/heero78/bravo/commit/d9600f164ea26c5393fb66e688bc3b1ca4780610
http://img861.imageshack.us/img861/6088/20110402200813.png

but i'm not good in python so the performance are bad (x2)

In the second screenshot we saw a light' lag  between the two tunnel. I think it'is because we set the "dims" of "Air" block at 0 and the "dims" of "Leaves" block at 1. 

```
blocks["air"].dim = 0
_add_block(Block(18, "leaves", drop=6, ratio=1 / 9, dim=1))
```

http://img839.imageshack.us/img839/2944/20110402203719.png

But when i use the nochian server :
http://img402.imageshack.us/img402/179/20110402200842.png

In my opignon, no block should have dim=0, but some block like glass must be ignored in the heightmap calculation.

http://img833.imageshack.us/img833/8745/20110403030828.png

An other bug is with the composite_glow function, It dosen't care about the "dims" value, so if we bury a torch, we can saw it's light.
http://img821.imageshack.us/img821/8995/20110402215558.png

The last thing, not realy a bug, but the skylight spread stop at the edge of the chunk
http://img43.imageshack.us/img43/4434/20110402215925.png

hope this help,

**Comment by MostAwesomeDude** [comment]
Well, let's go one at a time. (I really don't like these big compound issues.)

Whether or not leaves are supposed to be transparent was not really addressed very well in the "docs" on mwiki nor in the actual code. Apparently their effective transparency (and effect on lightmaps!) varies depending on whether graphics are set to fast or fancy. Your commit for fixing this looks decent, though.

The dim values come directly from the Notchian block definitions. They are not ours.

Block lighting is still iffy and needs to be fixed up. Nobody's complained much about it, though. What probably needs to happen is more spreading. Suggestions?

Yes, in some cases, lighting doesn't spread across chunk boundaries. I'm open to suggestions on how to fix this; the best way is probably to have a genuine chunk postprocessing stage that runs after chunks have all their neighbors generated.

**Comment by MostAwesomeDude** [comment]
Closing since this was addressed a long time ago and all the relevant patches have been merged.
