### ISSUE TITLE
/help not very helpful to clients.

### ISSUE THREAD

**Issue by actown** [bravoserver/bravo#188]
Looks ugly to ingame clients.

**Comment by MostAwesomeDude** [comment]
Adding to 1.4 milestone.

What should /help do?

**Comment by gtaylor** [comment]
A list of commands would be nice. Or an index that split into further sub-topics.

**Comment by alucas** [comment]
I think this could be fine :

/help -> "help, list, home, sethome, give" (list the alowed commands)

/help give -> "/give <block/item> [count] " + summary

/help help -> "/help [command]" + summary
