### ISSUE TITLE
Feature: Command line/In game command to change seasons.

### ISSUE THREAD

**Issue by actown** [bravoserver/bravo#19]
See title. (/)season (winter/spring/summer/fall) or something of the like.

**Comment by kyso** [comment]
Can it be that hard to implement? Haven't read that much, but can't you just call whatever changes the seasons by default?

**Comment by MostAwesomeDude** [comment]
Slightly tricky, as the seasons are indexed by date and not name, but I think this can be worked out.

**Comment by MostAwesomeDude** [comment]
Already done. There are some optimizations that I might get around to doing, but the legwork's done and committed.
