### ISSUE TITLE
Water from broken ice will disappear

### ISSUE THREAD

**Issue by JDShu** [bravoserver/bravo#205]
When you break a block of ice, the water disappears (when the water hooks are enabled).

**Comment by MostAwesomeDude** [comment]
Does this still happen? I never could reproduce this.

**Comment by JDShu** [comment]
Happens with the current bravo.ini example, when it is winter.

**Comment by oal** [comment]
Happens to me as well, but it looks like the water hooks don't make a difference. It happens both with or without. My world is new, and I haven't had the chance to test it on an old world.

**Comment by JDShu** [comment]
Took a look at it. It's because an ice block gets replaced by a water block when it's destroyed, as opposed to a spring. The simple solution would be to change that. Alternatively an ice block could save whether it is frozen water or frozen spring in the metadata.

**Comment by MostAwesomeDude** [comment]
The metadata trick sounds preferable.

Sending from a mobile, pardon the brevity. ~ C.
On May 17, 2011 12:18 AM, "JDShu" <
reply@reply.github.com>
wrote:

**Comment by MostAwesomeDude** [comment]
This was pulled in a long time ago. Closing.
