### ISSUE TITLE
Submodule

### ISSUE THREAD

**Issue by justinnoah** [bravoserver/bravo#209]
You say that tools shouldn't be packaged with bravo considering their quality. Why not make them a submodule, therefor optional?

**Comment by MostAwesomeDude** [comment]
They're useful for developers of Bravo, so I don't see why they need to leave the repo, and setuptools.find_packages() doesn't discover them, so I don't see the problem in leaving them in the repo.

**Comment by justinnoah** [comment]
... and setuptools.find_packages() doesn't discover them ...

sold.
