### ISSUE TITLE
Spawning.

### ISSUE THREAD

**Issue by kyso** [bravoserver/bravo#21]
Original spawn spot is high above the clouds on most, if not all generated maps. When a player saves above ground, their spawn spot is equally as high. If they are near bedrock, they seem to spawn lower then their actual spawn spot is located. If on bedrock, you are pretty much SOL as you fall through the bedrock.

**Comment by MostAwesomeDude** [comment]
I have a feeling that our Y coordinates are saved incorrectly, or with a bad offset, since I do seem to occasionally spawn inside the ground by around half a block. I'll see what can be done about this.

**Comment by kyso** [comment]
Err, whoops I closed it..
