### ISSUE TITLE
Dug areas become pitch black when logging back in to server

### ISSUE THREAD

**Issue by JDShu** [bravoserver/bravo#210]
After digging a hole, logging out of the server, and logging back in, the area that was dug will be pitch black. Placing a block nearby or digging out a block nearby will make everything look normal again but only until the next login.

**Comment by dbdii407** [comment]
I mentioned this to Mr. Awesome a couple of days ago in a pull request, along with a screenshot http://min.us/mvpmXyE . There is still some issues with lighting that need to be worked out. Trust me, it's being worked on.

**Comment by MostAwesomeDude** [comment]
This is a dupe of #132.
