### ISSUE TITLE
Change the IDigHook definition

### ISSUE THREAD

**Issue by ceymard** [bravoserver/bravo#221]
So far, we can't really process start dig events.

I suggested before the creation of another hook, but since it's the same packet underneath, it didn't really make sense...
Anyways, if we were to change the hook, there would be imo two ideas :
- Two interfaces : IBrokenHook when a block was digged and IDigHook becomes the new "Digging Started" hook (Or any other names that differentiate the two)
- Augment the dig_hook of IDigHook with.a last boolean parameter "broken" which is true when done digging.

This feature is necessary to properly implement doors since they are blocks and not entities and by such can not receive an action through use_hook (only with Dig and Build).

**Comment by squiddy** [comment]
If there is no interest to generalize use_hook to include blocks, I suggest to rename it to something more appropriate, like entity_attack_hook (what it mainly is).

**Comment by MostAwesomeDude** [comment]
This is blocked by #147.

**Comment by MostAwesomeDude** [comment]
I am quite in favor of the resolution which extends IUseHook to work with blocks. Also, with the dig policy being introduced on the dig-policy branch (see #147), we do not need a plugin interface for blocks which are being dug but which have not been broken.

Part of the fun of Bravo, as I see it, is the flexibility to have hooks which don't directly correspond to the wire. This is why we have both BSP and BravoProtocol. If there are semantics which we can paper over with a layer of abstraction, then we should do so.

**Comment by MostAwesomeDude** [comment]
Ping? Dig hook got changed, so this is technically fulfilled, but I want to know whether it's suitable for people now.

**Comment by ceymard** [comment]
I'll check it when I fix my pull request for the doors. Haven't had much time lately.

**Comment by MostAwesomeDude** [comment]
Closing. Please don't reopen without specific changes in mind; it's very hard to address "change this thing" as an issue.
