### ISSUE TITLE
Seasons might not properly change if the time is change by a user.

### ISSUE THREAD

**Issue by mythmon** [bravoserver/bravo#228]
If the user uses a command that modifies the time in the world, and skips over the first day of a season, then the effects of that season won't happen.

Example: Spring starts on day 90. If on day 89, I set the day to 91, the season will change to spring, but the ice won't melt.

**Comment by MostAwesomeDude** [comment]
Adding to 1.5 milestone. The basic technique should be to take the season-finding code from the Time command, and factor that out and test it more stringently, then use it to discover the correct season.

**Comment by MostAwesomeDude** [comment]
Fixed by recent patches.
