### ISSUE TITLE
TODO: Server-Side inventory.

### ISSUE THREAD

**Issue by actown** [bravoserver/bravo#23]
Check to make sure the client has said item compared to the save. Also make sure the client can pick-up items and make changes accordingly in its inventory file.

**Comment by MostAwesomeDude** [comment]
I'd like to put this off until Alpha rolls out its server-side inventory, since there will probably be a few changes to the protocol when this happens.

**Comment by actown** [comment]
Agreed, but it cant hurt to start thinking about it.

**Comment by MostAwesomeDude** [comment]
This is no longer optional, obviously. The groundwork has been laid; the packet parser handles everything correctly, the plumbing just needs to be added to BetaProtocol and Inventory.

**Comment by MostAwesomeDude** [comment]
Closing this bug. Open individual bugs for not-working things.
