### ISSUE TITLE
Built GH pages docs not updated

### ISSUE THREAD

**Issue by gtaylor** [bravoserver/bravo#231]
http://mostawesomedude.github.com/bravo/

Think this was supposed to be updated by the buildbot, but it's not. All my pretty doc updates aren't showing there yet.

**Comment by MostAwesomeDude** [comment]
GH doesn't really understand what it means that I deleted my pages repo. I'll figure it out at some point. Anyway, the buildbot points to http://www.docs.bravoserver.org/, not the GH page.

**Comment by gtaylor** [comment]
Ah, ok. You can just go to 'Admin', un-check the Pages option and it'll disable that. Or delete gh-pages branch. I'll send a pull request with that URL updated in the README.
