### ISSUE TITLE
GH project website -> http://mostawesomedude.github.com/bravo/

### ISSUE THREAD

**Issue by gtaylor** [bravoserver/bravo#232]
For now, it'd be great to have the GH project's website link set to the documentation. I know there's a one-page site that exists for Bravo, but until that shapes up more, the docs may be more helpful.

http://mostawesomedude.github.com/bravo/

**Comment by MostAwesomeDude** [comment]
I'm loathe to set this for 1.5, since I might not get to it, but I've been planning on beefing up bravoserver.org slightly.

**Comment by gtaylor** [comment]
Doesn't need to be permanent, by any means, but having a links to the docs for now might be better than nothing. People have to do an awful lot of scrolling/reading on the landing page to find the docs link atm.

**Comment by MostAwesomeDude** [comment]
So, at this point, bravoserver.org is up, running, and automated. I think I'm gonna close this as fixed by runaround. :3
