### ISSUE TITLE
Damaged items are repaired

### ISSUE THREAD

**Issue by progval** [bravoserver/bravo#238]
Hi,

If I have a damaged item (sword, shovel, pickaxe, and so n), and I pick an item (grass, dirt, stone, and so on), all the damaged items are repaired.

Regards,
ProgVal

**Comment by progval** [comment]
Reconnecting to the server also repairs the items.

**Comment by alucas** [comment]
Damages are not already tracking in bravo.

**Comment by MostAwesomeDude** [comment]
Closing as a duplicate of #70.
