### ISSUE TITLE
Regression: Breaking some blocks cause client to lockup and crash.

### ISSUE THREAD

**Issue by actown** [bravoserver/bravo#24]
While breaking snow and ice clients lock-up and crash. Dirt works fine, everything else untested.

**Comment by MostAwesomeDude** [comment]
d93927be3714fadb4ad32fe9ed332070a0cc5618 fixes it for me. I'm going to separate that code out into a new dig hook so that it's easier to disable and test.

**Comment by MostAwesomeDude** [comment]
All done; all dig actions are handled in hooks.
