### ISSUE TITLE
Water dig hook needs to be improved

### ISSUE THREAD

**Issue by progval** [bravoserver/bravo#246]
Hello,

The "water" dig hook does not handle water falls, as seen in this [screenshot](http://ompldr.org/vOGo4Ng/Capture-2.png).

Regards,
ProgVal

**Comment by MostAwesomeDude** [comment]
Hard to see the sequence of events there. I'll add a waterfall test.

**Comment by JDShu** [comment]
ugh, I'm sorry, didn't realize github would automatically attach this here.

**Comment by MostAwesomeDude** [comment]
Ah, figures that GH wouldn't understand that this was part of 1.5. Hopefully we're all finished with this now.
