### ISSUE TITLE
Light not updated when using /time

### ISSUE THREAD

**Issue by progval** [bravoserver/bravo#248]
Hello,

I was night, and I used "/time 0". Here is the result: http://ompldr.org/vOGp1aQ

Regards,
ProgVal

**Comment by progval** [comment]
PS: it gets updated when I put a dirt block.

**Comment by MostAwesomeDude** [comment]
I'm not sure if this is a client bug or not. Something to examine later, I think.

**Comment by MostAwesomeDude** [comment]
This is a dupe of #132, plus a client bug which will require more thought to work around.
