### ISSUE TITLE
Player's Y spawn position is ignored

### ISSUE THREAD

**Issue by squiddy** [bravoserver/bravo#254]
Players are spawned at the tallest point in the x,z position in a chunk. `Protocol.update_location` is responsible for that. It should consider the y position of the player, but as a safety feature, check whether there is enough room for a player standing.

@heero78 has a branch (https://github.com/heero78/bravo/commits/physical_blocks) that seems to be a possible solution.

**Comment by MostAwesomeDude** [comment]
Yeah, while I'm not super-fond of that physical_blocks branch, I do agree that this is important. Tagging for 1.6.

**Comment by mcsakoff** [comment]
I think the hollow blocks look good. We can use it not only for spawn position.
