### ISSUE TITLE
Support for beds

### ISSUE THREAD

**Issue by squiddy** [bravoserver/bravo#255]
As of now I have code for placing/destroying beds, that I hope to get accepted for 1.6. What else makes up support for beds probably needs discussion.

**Comment by MostAwesomeDude** [comment]
Adding to 1.6.

**Comment by mcsakoff** [comment]
squiddy, may I see the code?

Update: Nevermind. I found the branch.

Update2: Don't you mind if I pull your branch and re-work it a little bit? I'm not happy about facing things.

**Comment by squiddy** [comment]
@neenar Sure! It probably won't merge without conflicts anyway. I think I had more code somewhere, I'll let you know if I find anything.

**Comment by MostAwesomeDude** [comment]
Merged enough to the point where we could have finer-grained bugs for this. Closing for 1.8.
