### ISSUE TITLE
furnaces working?

### ISSUE THREAD

**Issue by caphrim007** [bravoserver/bravo#261]
I'm attempting to place a furnace and get it to work. When I place the furnace, the face of it disappears, and clicking on it brings up no window. If I destroy it and pick it back up, it +1's the furnace item in my inventory though, so something thinks it's a furnace.

I'm using a pull of the github repo from when 1.5 was bumped

Ideas?

**Comment by squiddy** [comment]
Yeah, furnaces aren't fully supported yet.

I plan to improve support for chests for 1.6 (to be released in about 2 weeks), and I do want furnaces to work. If no one else works on it, I'll try.

**Comment by caphrim007** [comment]
Ok, I wasn't sure if it was me, or something else. I'm still in the early stages of understanding bravo, otherwise I'd offer to work on it.

**Comment by MostAwesomeDude** [comment]
Furnaces are only oriented if placed against a wall and not on the floor. Fixing that would merely require a small build hook to turn it to face the player, similar to the tracks build hook.

Furnace smelting isn't supported at all. Marking this as a tracker for that feature and tagging for 1.6.

**Comment by mjevans** [comment]
What sort of work would be necessary to implement furnaces within Bravo, and are there generic pointers to the documentation?  I really don't have the time to even try this in the short term, but if it languishes until I once again have time I'll try it my self since it's one of the few major issues blocking my use of Bravo.

**Comment by mcsakoff** [comment]
Implemented. I will test for day or two and will create pull request.

**Comment by MostAwesomeDude** [comment]
Closing in the hope that the recent inventory patches are sufficient for this.
