### ISSUE TITLE
Need synchronisation

### ISSUE THREAD

**Issue by alucas** [bravoserver/bravo#267]
The digging process can take several seconds (so bad :x).

When the latency is too high the client think the packet was lost, so he rebuilt the block. In this case we can re-dig the blocks and therefore, with the "give" plugin, we got 2 drop.

**Comment by alucas** [comment]
Note: the latency is just a digging policy imperfection (don't take care about tools), sorry.

**Comment by MostAwesomeDude** [comment]
Yeah, the big thing here is not letting the client double-dig blocks. That's important.

**Comment by MostAwesomeDude** [comment]
Closing as addressed by the dig policy work.
