### ISSUE TITLE
Block Placement Inside Players

### ISSUE THREAD

**Issue by emberian** [bravoserver/bravo#268]
Currently, you can place blocks "inside" yourself and other players (look down, place two blocks). From the little I've looked into it, it should be simple to modify bravo.plugins.build_hooks.Build to prevent placing a block inside your self (I have a patch in the works, needs slight refinement and tests). I didn't see an obvious solution to prevent placement of blocks inside _other_ players. Thoughts?

**Comment by dliverman** [comment]
I had a fix for this a while ago.  It needed to be cleaned up but I haven't gotten around to it.  One of the things I noticed was that your location is stored as an int for (x,z) and a float for (y).  So even with the patch you can still place boxes that clip if you stand at (1.99,1) and place a block at (2,1).  However, after a lot of block spamming, it didn't happen THAT much, I'm not sure how wide the player is.

**Comment by emberian** [comment]
dliverman: I didn't notice anything different in build_hooks.py (where I am putting my fix), so is your fix not in your fork or is it long gone?

**Comment by dliverman** [comment]
KB1PKL: My branch got hosed.  Was a plugin that checked if player x,y,z intersected block x,y,z then interrupted the build.  Was player only.  I haven't looked at how other entities are handled yet.
