### ISSUE TITLE
Beta network compression

### ISSUE THREAD

**Issue by MostAwesomeDude** [bravoserver/bravo#290]
Figure out what it is, how it works, whether it matters to us, etc.

**Comment by gtaylor** [comment]
"notch: Changing the gzip compression level reduces bandwidth by some 30%, but increases cpu time spent compression.. Hmmm.."
--http://twitter.com/notch/status/72939674179604480

**Comment by MostAwesomeDude** [comment]
Oh, whatever, then. We don't send the gzipped ones very often, and
benchmarks and profiles have _never_ incriminated gzip. This might be a
non-issue.

Sending from a mobile, pardon the brevity. ~ C.
On May 26, 2011 7:31 AM, "gtaylor" <
reply@reply.github.com>
wrote:

**Comment by gtaylor** [comment]
Yeah, I'm not concerned with gzip. We gzip 100,000+ web transactions a day on some pretty terrible hardware without any issue. However, it appears that gzip is at least one piece of the puzzle to Beta network compression. Figured I'd just post there here in case you don't hawk notch's Twitter account like me :)

**Comment by MostAwesomeDude** [comment]
Closing. We have ascertained that it completely and totally doesn't matter to us. :3
