### ISSUE TITLE
Most blocking issues (that is, game-breaking) brainstorm issue

### ISSUE THREAD

**Issue by mjevans** [bravoserver/bravo#293]
For me, there are a few readily obvious issues that ruin the fun and thus my desire to further test the current server.

Bravo
+++ Crafting tables worked this time I checked (at least with the 1.6.5 client)

Uh-ohs
(already covered in other issues)
--- Chests don't work (for me, with my current client anyway)
--- Furnaces are still unusable which holds me right in the stone age and stops me from making any of the more fun materials.
- odd snow glitches (this is back, registered public can't re-open old issues)

Block-item issues
+/- This time I can collect blocks that drop from at least one block above my head, but the block /right/ above my head seems to spin uselessly beneath me no matter how much I jump.
- block gravity/collection far more fluid with other servers.
  Wooden doors don't drop doors when axed? (or was this just a one time glitch; it did shift between closed and open during my click.)

For me, most of the other issues now slot in to 'annoying', chests and furnaces are the two major killer issues.

**Comment by gtaylor** [comment]
You'll definitely want to open separate issues for these, though many already have issues open. Discussions are best sent to the mailing list, if that's what you're looking for.

**Comment by MostAwesomeDude** [comment]
Metaissues aren't helpful.

#256 and #261 already track chests and furnaces, respectively. #7 is reopened for tracking build_snow problems.

There is no bug for "Pickups do not obey gravity" and I don't plan to work on it in the near future as it's a lot of work. Open it if you want it.

There is no bug for door problems, but considering the relative lack of testing of the doors plugin, I would not be surprised if it has issues. Open issues for those, please.

Oh, and for testing purposes, you can always /give whatever you want.

**Comment by MostAwesomeDude** [comment]
Oh, there's a bug for pickups and gravity: #153.
