### ISSUE TITLE
Multiple port/interface binding

### ISSUE THREAD

**Issue by MostAwesomeDude** [bravoserver/bravo#295]
It should be possible to bind multiple times with a single factory. We need configuration support for this.

**Comment by EntityReborn** [comment]
I've added a pull request which supports ports. I haven't done anything in terms of interfaces yet tho.
EDIT: I've included interfaces now. See https://github.com/MostAwesomeDude/bravo/pull/296

**Comment by MostAwesomeDude** [comment]
Let's take a step back. What should the configuration look like? I'm a fan of requiring endpoints. They move the burden of formatting and parsing _out_ of Bravo, and into Twisted.

```
[world hurp]
interfaces = tcp:25565, tcp:25566:interface=lan
```

Anything else that I can think of at this point seems really hacky in comparison. Thoughts?

**Comment by MostAwesomeDude** [comment]
Bumping to 1.7 for configuration changes.

**Comment by EntityReborn** [comment]
I tried this method, but didn't have much success. the stringToServer method doesn't return a service, making things tricky. I'll look into this further.

**Comment by MostAwesomeDude** [comment]
You want twisted.application.strports.service(description, factory), which creates a service from an endpoint description and factory.
