### ISSUE TITLE
Low-RAM environment safety

### ISSUE THREAD

**Issue by MostAwesomeDude** [bravoserver/bravo#303]
For, say, a Wii, or more seriously, a Guruplug. We should be comfortable in a 64MiB environment, if we're careful about our RAM usage. This will obviously require some thought, but we can do this, with some planning.

**Comment by MostAwesomeDude** [comment]
Change of plans. Turns out that nobody was serious about this.

**Comment by justinnoah** [comment]
Not sure if anyone knew of this... I do like the idea.
