### ISSUE TITLE
Lava lake drains if an adjacent block is removed

### ISSUE THREAD

**Issue by Smallergamer** [bravoserver/bravo#312]
I removed a block from the edge of a lava lake and the whole lake was pushed back like air was pushing it into nothing. I also tried this on other lakes to the same result.

**Comment by MostAwesomeDude** [comment]
Does ced04cdd0c6e57c99eacf9d0677877e15fddb78c help at all?

**Comment by Smallergamer** [comment]
Sorry, but what is ced04cdd0c6e57c99eacf9d0677877e15fddb78c.

**Comment by MostAwesomeDude** [comment]
It's a commit in git. Make sure your tree has it, and test again. (Try clicking it!)

**Comment by MostAwesomeDude** [comment]
Closing as unreproducible and unresponsive.
