### ISSUE TITLE
Error Connecting To Server

### ISSUE THREAD

**Issue by MikePM** [bravoserver/bravo#316]
[bravo.amp.ConsoleRPCFactory] No module named 'bravo.parameters' in mapper < exocet._exocet._PEP302Mapper object at 0x01E6AED0 >

Also 'No module named 'PIL' (same error just a different module)

That's what I'm getting when the run start.bat

When I try to connect to the server I'm getting this: http://i.imgur.com/VIhvK.png
then an End of Stream error on Minecraft.

**Comment by MostAwesomeDude** [comment]
Not having PIL (python-imaging) installed only breaks one of the web services, not anything central.

Read the FAQ (http://www.docs.bravoserver.org/faq.html#configuring) for information on the things you're seeing. Basically, you need to add a world to your bravo.ini; by default, Bravo doesn't deploy any worlds, just an RPC console.

**Comment by MikePM** [comment]
How do I add a world to it?

**Comment by TkTech** [comment]
Github issues are not game support. Go check out the [very extensive documentation](http://www.docs.bravoserver.org/index.html).

**Comment by MikePM** [comment]
Wow you're fast, nevermind I fixed it anyway.
My bravo.ini got messed up somehow.

**Comment by TkTech** [comment]
That's what she said.
...wait...

**Comment by MikePM** [comment]
:P
