### ISSUE TITLE
PiP

### ISSUE THREAD

**Issue by TahMahn** [bravoserver/bravo#32]
"PIP install Bravo"

The above isn't working anymore.

**Comment by TahMahn** [comment]
Nevermind, just me being stupid.. again..

**Comment by MostAwesomeDude** [comment]
Nah, you're right. The package on PyPI is still called Beta, so installing from PyPI isn't currently possible. I need to take down the Beta package and upload a Bravo package. I was hoping to have 2.0 ready by now, but I may have to tag 1.0 now and do 2.0 in another week. Family gatherings have really cut into my coding time.

**Comment by TahMahn** [comment]
No problem mate, you're doing a great job anyways, so just take your time : )

**Comment by MostAwesomeDude** [comment]
Uploaded Bravo 1.0 to PyPI. Have fun.
