### ISSUE TITLE
Ore generation is slow

### ISSUE THREAD

**Issue by Krenair** [bravoserver/bravo#341]
Ore generation is slow and maxes out CPU cores for a while.

A friend had the same issue (his specs here: http://whendowegetthededi.co.cc/ ):
Azelphur: I tried enabling it last night but it 100%'d the server.

**Comment by MostAwesomeDude** [comment]
Ores are generated roughly the same way that the "complex" generator works, and are correspondingly slower than "simplex" by around 128x. It's a spendy set of operations.

I'd like to just say that it'll be far faster under PyPy, but that's not really much of a comfort for you right now. If you can find any way to speed it up, or an alternative algorithm which produces acceptable results, then I'd be interested.

**Comment by MostAwesomeDude** [comment]
Renaming to make it more obvious what the problem is here.

**Comment by MostAwesomeDude** [comment]
PyPy absolutely demolishes the benchmark for ore generation. I'm going to just mark this down as a case of "use PyPy" in the docs.
