### ISSUE TITLE
Painting directions are magical

### ISSUE THREAD

**Issue by MostAwesomeDude** [bravoserver/bravo#379]
We really could use some sort of enumeration there.

**Comment by apvsalvado** [comment]
First, I would like to say I admire you're doing a server Minecraft as stable with an advanced language such as Python.

And give a suggestion to create a forum so we could have more freedom to discuss some things about Bravo.

**Comment by gtaylor** [comment]
@apvsalvado http://lists.bravoserver.org/listinfo.cgi/bravo-dev-bravoserver.org

**Comment by MostAwesomeDude** [comment]
Recent changes have made it so that paintings simply use the same data as facing information for other blocks and such.
