### ISSUE TITLE
Immediate Terrain Generation

### ISSUE THREAD

**Issue by justinnoah** [bravoserver/bravo#42]
Bravo should probably begin generating terrain as soon as the server starts rather than waiting for a player to connect to begin.

**Comment by Varriount** [comment]
Yes, but what terrain, and where would it be generated? I can imagine that an area (Specified in the config?) might be loaded into memory on startup, to allow faster load times. Doing this, you could even load an entire world into ram (Given that you have enough ram)

**Comment by justinnoah** [comment]
How about the area around the spawn point to start?

**Comment by Varriount** [comment]
Well, yes.

**Comment by MostAwesomeDude** [comment]
I am thinking of consolidating the two ideas and having a setting on the World to always keep the area around spawn loaded in memory. Upon startup, it would cause terrain to be generated.

**Comment by MostAwesomeDude** [comment]
Done. There's now a permanent chunk cache, and a config option.
