### ISSUE TITLE
Tests should not trigger OOB chunk access

### ISSUE THREAD

**Issue by JeppeKlitgaard** [bravoserver/bravo#423]
When the server is run (without previous world, haven't tested with), or when running the tests it will continuously **_spam**_ `"Coordinates %s are OOB in %s() of %s, ignoring call"`-like messages. 

This is because the coordinates fail to the validation going on in `chunk.py:34`
This is something I think is rather alarming, and should be fixed.

**Comment by MostAwesomeDude** [comment]
It is definitely alarming, and if I had any gumption to hack on Bravo, I'd go and fix some of them. Patches welcome. Note that this bug cannot _ever_ be closed as worded, but that's okay; somebody will close it when messages get down to an acceptable level.

Edit: Updated title to have a measurable goal.
