### ISSUE TITLE
XML-RPC

### ISSUE THREAD

**Issue by justinnoah** [bravoserver/bravo#43]
More XML-RPC calls need to be made available.

XML-RPC calls might allow:
Get a list of commands
Run those commands
Get a list of players
possibly more....

**Comment by MostAwesomeDude** [comment]
All added as AMP RPC commands. The code needs to be armored up, but it works well enough for the consoles, which I rewrote to work over AMP.

**Comment by justinnoah** [comment]
Why the change to AMP?

**Comment by MostAwesomeDude** [comment]
AMP's easier to maintain, slightly more rigorous, and speedier.
