### ISSUE TITLE
Problem installing Bravo

### ISSUE THREAD

**Issue by footydave09** [bravoserver/bravo#45]
Hello, I have tried install Bravo onto a fresh install of Ubuntu, Here is a screenshot of the error that I received when I asked pip to install bravo

"pip install Bravo"

http://i670.photobucket.com/albums/vv61/Footydave09/Error2.png

Thanks in Advance

**Comment by Varriount** [comment]
I should think this is fairly simple. Look at the bottom line. You need the python development package to compile the modules. Look in your package manager.

**Comment by MostAwesomeDude** [comment]
You should use the numpy provided by Ubuntu. I think the package is called "python-numpy". Unfortunately, pip doesn't know how to do this; it only knows how to go build things from source directly.

I used to have per-distro installation instructions; maybe I should add them back in?
