### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by tom-spalding** [bravoserver/bravo#454]
http://bravoserver.org website is down

but you probably already knew that. :smiley:

**Comment by edunham** [comment]
Thanks for the heads up!

The site is currently working for me... check your connection?  Odds of getting @actown to implement and then respond to monitoring are poor.

**Comment by tom-spalding** [comment]
Ha, okay [it is just me](http://www.downforeveryoneorjustme.com/bravoserver.org), weird.

**Comment by micahh2** [comment]
Odd, it seems down for me as well.

**Comment by actown** [comment]
I do have monitoring setup, just not for bravoserver, I can see whats up as it didn't work for me. Looks like a possible DNS issue.
