### ISSUE TITLE
Mob entities + Hooks

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#46]
We need some mob entities, such as creeper, as well as hooks to be run when an entity is created.

**Comment by MostAwesomeDude** [comment]
Odds are pretty good that an entire IMobFactory interface will be introduced, which will let us make classes that spit out IMobs. This is very similar to the setup in the Notchian server, but we'll be truly polymorphic, which should give us a lot more flexibility. Notchian mobs only have a handful of methods, so this shouldn't be _super-hard_.

**Comment by MostAwesomeDude** [comment]
Metadata can now be parsed, as of 15972d7743454aa3b9a8b9f08bad228d3c8c10cd, so if people start getting me the metadata from Notchian mobs, I can start implementing the proper stuff for getting them to show up on-screen.

**Comment by MostAwesomeDude** [comment]
A better metadata parser was merged today, and I now have enough metadata stubs to start implementing mobs. It'll be a bit, though.

**Comment by MostAwesomeDude** [comment]
Sheep are now implemented. Expect the other mobs shortly.

**Comment by MostAwesomeDude** [comment]
Done to the point where additional mobs can (and should!) get their own issues. Further improvements, like AIs, will have to wait for Bravo 1.5.
