### ISSUE TITLE
Redstone

### ISSUE THREAD

**Issue by actown** [bravoserver/bravo#49]
Redstone stuff.

**Comment by MostAwesomeDude** [comment]
Some very small steps have been done in this direction, but not enough. Need to keep working on this.

**Comment by Varriount** [comment]
I can't help but think that notch's crazy recursive physics technique might have to be implemented for redstone...

**Comment by MostAwesomeDude** [comment]
I'm not sure why you would think that. All recursive algorithms can be turned into iterative algorithms, and this one is no different.

Every time a redstone-related block is changed, mark it.

Every step, for every marked block, change the blocks around it, and unmark it.

That's it. The trick is implementing those two functions correctly.

**Comment by Varriount** [comment]
That's what I meant... I even suggested something like that for physics before, and you nixed it.

**Comment by MostAwesomeDude** [comment]
Okay, so a status update's probably a good idea. I have enough redstone working to do levers and NOT gates, and there are unit tests for them. I don't have time to pound out the rest of it, but be assured that I haven't given up.

**Comment by MostAwesomeDude** [comment]
So now here's where we are: The new structures, with circuits, work well. Wires need to be added, but otherwise we're set. Things are just _fantastic_.

**Comment by MostAwesomeDude** [comment]
Work on wires has happened. We are at a slight impasse; the semantics of a couple of creative wire usages need to be cleaned up. Once that's happened, we are probably alright to implement the rest of the simple circuit tests and consider further improvements on a per-circuit basis.

**Comment by MostAwesomeDude** [comment]
Closing as "fixed." Redstone is now a supported feature of the server and deserves to be treated as first-class when it comes to issues. Further improvements to redstone can have their own issues.
