### ISSUE TITLE
Near impossible installation on windows

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#50]
Yes, yes, I know that I should use Linux. Fact is, though I dislike it, windows dominates the market. Currently installation of all modules bravo needs, then setting them up, then getting bravo to work, is almost plain impossible. We need a guide and ways to simplify installation. Getting users to install mingw32 is good, if we can get setup.py to work as well. Links to appropriate downloads would also be an alternative.

**Comment by MostAwesomeDude** [comment]
Write me some documentation. I'll handle the grammar and formatting, but I don't know the actual steps and I don't have Windows machines to test with. I literally do not have a single Windows box under my control.

**Comment by LIII-XXII** [comment]
Same here. I've used Ubuntu a couple times, so I will consider running Bravo on Linux using Virtualbox... but it'd be best in windows. 
I've installed Python (never used it before in windows), downloaded Bravo...
And now I don't understand what I should run.

Start.bat does not work (the variables used are not set properly or stuff is in the wrong place I guess).

run_benchmark.py goes :

<pre><code>
C:\Users\Florian>D:\Bureau\MostAwesomeDude-bravo-b86018c\run_benchmarks.py
Traceback (most recent call last):
  File "D:\Bureau\MostAwesomeDude-bravo-b86018c\run_benchmarks.py", line 15, in
<module>
    stdout=subprocess.PIPE).communicate()
  File "C:\Python27\lib\subprocess.py", line 672, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 882, in _execute_child
    startupinfo)
WindowsError: [Error 2] Specified file not found
</code></pre>


I guess a guide for setting up Bravo in Windows would deal with setting up both Python and the server itself to work together.

(That's when you can't use sotfware from awesome dudes that you seriously consider using linux... ;p)

P.S : I can translate the guide into french once it's done.

P.P.S: Woops, I forgot to install Twisted... It's done now. :)

Start.bat goes :

<pre><code>D:\Bureau\MostAwesomeDude-bravo-b86018c>ECHO OFF
Please specify your version of python: 'Python26', 'Python25', or 'Python27'Pyth
on27
Specified path cannot be found.
Press any key to continue...

D:\Bureau\MostAwesomeDude-bravo-b86018c>
</code></pre>


run_benchmarks.py still does not work either.

**Comment by Varriount** [comment]
I have a guide in the works, I could send you that. It's not complete. What error do you get with the bat file?
Have you added python to your path environment variable?
Have you downloaded easy_install?
If you can wait a couple days, or come on irc at around 3:30 eastern time, I can give you personal help

**Comment by LIII-XXII** [comment]
What time is 3:30pm eastern time ? It's UTC-5 right ? It's UTC+1 here (I live in France), that makes it 9 am... I'm afraid that's too soon for me.
I did not download easy_install nor did I add C:\python27\ to %path%, I'll do it as soon as I get home...
Please send me your version of the guide, that'll help me for the basics.

Thanks !

**Comment by justinnoah** [comment]
Instead of installing, here is a build I keep relatively up to date. At the time of writing, it is current.
http://brutal-chaos.github.com

I am also working on a script, something similar to pip/easy_install that will go and grab the bravo deps for you, for now the script just tells you what you need.

**Comment by Varriount** [comment]
Heres a (Incomplete) Copy of the guide. I think what you need to do is add python to your path variable, thats what most likely causing the issue. Don't be afraid that the guide is long, its just very detailed. We window's users aren't always the brightest. :p
http://pastebin.com/8rFreagp
EDIT: Ah, I think it may be because of your system (French?) The bat isn't finding the right path. just go to your python path and open the scripts folder, copy twistd.py to the folder that has the start.bat and then run the bat file. That should do it

**Comment by LIII-XXII** [comment]
Sorry Varriount

<pre><code>- Unknown paste ID, it may have expired or been deleted!</code></pre>


Adding C:\python27\ to %path% isn't enough, now start.bat now goes <pre><code> 'python' is not recognized as an internal or external command, executable program or batch file.
Press any key to continue...</code></pre>

I don't think the language is to be blamed, it's just a frontend.

@Brutal-Chaos : Is your build the last version ? It seems to work fine and people can join, but chests and creeps/monsters don't work.

I tried to run the server specifying everything and it now goes :

<pre><code>

C:\Users\Florian>cd C:\Python27

C:\Python27>python D:\Bureau\MostAwesomeDude-bravo-b86018c\twistd.py -y D:\Burea
u\MostAwesomeDude-bravo-b86018c\bravo.tac
Traceback (most recent call last):
  File "D:\Bureau\MostAwesomeDude-bravo-b86018c\twistd.py", line 18, in <module>

    from twisted.scripts.twistd import run
  File "C:\Python27\lib\site-packages\twisted\scripts\twistd.py", line 11, in <m
odule>
    from twisted.application import app
  File "C:\Python27\lib\site-packages\twisted\application\app.py", line 7, in <m
odule>
    from twisted.python import runtime, log, usage, failure, util, logfile
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 17, in <modul
e>
    from zope.interface import Interface
ImportError: No module named zope.interface
</code></pre>

**Comment by Varriount** [comment]
That error from that bat means that you added python to the path variable wrong. You might have to restart your computer.. Also, the link must have gotten malformed in the git-hub markup, here should be the correct hyperlink..
Also, I stress that at the time of this writing, I'm on irc and should be on for another 5 hours. address is freenode on #bravo
Tested it myself this time too
As for the win executable, you will need to install zope
http://pastebin.com/8rFreagp
