### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by justinnoah** [bravoserver/bravo#52]
setup.py isn't grabbing the plugins when installing, it doesn't grab serializers or tests either.

**Comment by MostAwesomeDude** [comment]
Fixed.

**Comment by justinnoah** [comment]
Actually, this isn't fixed.

**Comment by MostAwesomeDude** [comment]
Doesn't dbaf24bf06edaeaaf769b15ecc8801d8f075db9c fix it for you?

**Comment by Varriount** [comment]
It's fixed for me, though depending on your linux distro, python may look in odd places for modules.
