### ISSUE TITLE
cpu usage with JSON

### ISSUE THREAD

**Issue by bitcraft** [bravoserver/bravo#58]
Not sure what can be done about this, but on a small server simplejson is killing my cpu.  Heres a profile I took of my client on python 2.5.

http://pastebin.com/Z9g7Ha0N

I'll look into alternatives over the next couple days.

**Comment by MostAwesomeDude** [comment]
Simplejson's pretty bad if you don't have the C extensions; the Python 2.6 json module's a lot speedier. Still, JSON bites in terms of performance. It was meant to be an OOB solution, but it's causing two problems for every problem it solves. I'd like to add BSON at some point, but we might want to sit down and think first.

**Comment by MostAwesomeDude** [comment]
NBT is now the default serializer, which makes this moot. JSON's only for debugging now.
