### ISSUE TITLE
Other player(s) not showing up.

### ISSUE THREAD

**Issue by actown** [bravoserver/bravo#6]
When more then one player is connected, the other player(s) do not show up.

**Comment by MostAwesomeDude** [comment]
This is almost certainly because we do not broadcast player entities. I'll fix this in a few days.

**Comment by actown** [comment]
I figured it was something along those lines. The "issue" was intended as more of a reminder as we really only test with one player on the server.

**Comment by MostAwesomeDude** [comment]
The correct packets are definitely getting sent. Whether or not they work correctly has yet to be determined. We can reopen if it doesn't work. :3
