### ISSUE TITLE
WIndows Errors on startup

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#60]
I get this error on startup
I'm pretty sure that this may have something to do with the windows filesystem enviromental variables, or the quirkiness of windows in general.

https://gist.github.com/784947

**Comment by justinnoah** [comment]
I believe after that error, bravo still runs. As far as I can tell, it's ignorable.

**Comment by MostAwesomeDude** [comment]
The first error was in setup.py and is fixed. The second error is a harmless Win32-specific error that does not appear to affect things. Justin and I already talked it over; it should be fine. Closing.
