### ISSUE TITLE
Feature: Fire

### ISSUE THREAD

**Issue by actown** [bravoserver/bravo#61]
Another thing to add is fire. Would be awesome if it is a plugin and you can configure it from the bravo.ini. Such options might include to disable fire, to disable fire from spreading, etc.

**Comment by Varriount** [comment]
Actually, this should be easy using cellular automata. Fire starts, checks for spreadable neighbors, and spreads. Interesting thing will be how things burn.. Maybe selecting random entries from a list of fire blocks and puttin them out.
