### ISSUE TITLE
Bravo dependencies include the mythical "reconstruct"

### ISSUE THREAD

**Issue by mojomojomojo** [bravoserver/bravo#62]
I installed a minimal debian machine from scratch. I built and installed Python 2.6 from source.
I tried installing Bravo via pip for Python 2.6. pip insisted that Bravo needed reconstruct, which it couldn't find. I installed construct via pip, and it completed without problems. pip still was unsatisfied with construct and wouldn't install Bravo without the impossible reconstruct. I installed it without dependencies, and when I attempted to run it, surprise! It wanted reconstruct. Hmm... I edited Bravo-1.0-py2.6.egg-info/requires.txt and changed "reconstruct" to "construct". Now Bravo starts.

I don't know enough about Python to suggest what's still wrong with the distribution. I assume you do. If this is something I'm doing incorrectly, I'm mentally prepared to 'fess up to my own ignorance.

**Comment by Varriount** [comment]
Are you using the git source, or using something like easy_install bravo? The current package on the Python Package Index is outdated. I've never had to install reconstruct, though I have found the page for, after a quick search on google. http://pypi.python.org/pypi/reconstruct/2.03dev

**Comment by mojomojomojo** [comment]
I was using pip (mostly because the documentation recommended it).
I was trying to keep this machine as small as possible, so I didn't want to install git unless it was really necessary.
The problem with reconstruct is that it won't install.

I suppose you'd recommend then, that I use git to grab the files and install. OK, I'll do that.

**Comment by MostAwesomeDude** [comment]
Reconstruct has been halted since Construct has a new maintainer now (me, actually.) I've just pushed Bravo 1.1, which depends on Construct 2.03 or newer and should pull down deps just fine. (Lemme know if it doesn't work.)
