### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by justinnoah** [bravoserver/bravo#66]
Basically, it doesn't work. Try anything like torches, or something that produces more than one item, weird infinite amounts occur or sometimes things disappear. Looks like there _may_ be a pattern to it though.

**Comment by MostAwesomeDude** [comment]
This is an incredibly useless issue report, especially since the inventory _does_ work in the vast majority of cases. Feel free to contribute tests showing the problem.

**Comment by justinnoah** [comment]
I will write a test. Where are docs on how to write a test dealing with inventory?
