### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by justinnoah** [bravoserver/bravo#68]
Various lighting bugs, including a very bright moon.

**Comment by MostAwesomeDude** [comment]
I'm sorry, what? Can you be more specific? The sun and moon are not under server control.

**Comment by Varriount** [comment]
Well, I have found that certain areas of the map can get out of sync, with some areas being day when its night, and vice versa. In addition, during night, various dirt blocks become light source, until they are destroyed.
Here are some lighting bugs that I have seen. None of them give an error however.
http://dl.dropbox.com/u/4843432/pinpointlights.png
http://dl.dropbox.com/u/4843432/untitled.png

**Comment by justinnoah** [comment]
Here is an example of 'bright moon'
http://i.imgur.com/UIZHF.png

**Comment by justinnoah** [comment]
Here is a set of images from the transition of night to day and the effects.

Night:
http://i.imgur.com/UAFL1.png

Day (after night):
http://i.imgur.com/9YjwI.png

**Comment by MostAwesomeDude** [comment]
The bright moon link is dead. All of these lighting bugs are relatively reproducible; if you have any suggestions on improving the lighting code or tests, I am all ears as long as they are more informed than "Fix it and make it work better."

**Comment by justinnoah** [comment]
Ok. Ignore the bright moon link being dead, the idea comes across in the night link.

**Comment by MostAwesomeDude** [comment]
I'm closing this. If you have specific suggestions or ideas, please tell me or write some code. Lighting is hard.
