### ISSUE TITLE
Stairs

### ISSUE THREAD

**Issue by justinnoah** [bravoserver/bravo#69]
No matter how stairs are placed, they 'rotate' and all stairs always face the same direction.

**Comment by MostAwesomeDude** [comment]
Need a Stairs build hook to realign their metadata.

**Comment by MostAwesomeDude** [comment]
Stairs are oriented now, although they really should get the same treatment as tracks due to how people typically place them, and also considering that there _are_ rules for stair placement.

**Comment by MostAwesomeDude** [comment]
Assigning to 1.7; let's see if we can get this done.

**Comment by justinnoah** [comment]
This would be part of the data, yes? If so, wouldn't we just take the negative of the way the player looks (assuming the front of the stairs is the direction they point) and apply it to the data of the stairs? For example if the Player is looking North, the Stairs point south. Or is it a bit more complicated than that?

EDIT: I should read comments before posting....

What's wrong with the way they are now if they work?

**Comment by MostAwesomeDude** [comment]
Closing since apparently everybody's happy with the way they work, even if it's not Notchy. This has been open for a long long while, so I'm all-too-happy to close it. :3
