### ISSUE TITLE
Placing a block on snow causes weird block issues.

### ISSUE THREAD

**Issue by actown** [bravoserver/bravo#7]
When you place a block on top of a snow covered block, many weird issue happen such as the block moving up one space and the snow returning.

**Comment by MostAwesomeDude** [comment]
Snow isn't a replaceable block; that is, if you place something _on_ snow's top, it is replaced by the block that was placed. We should figure out whether there are any other replaceable blocks first.

**Comment by MostAwesomeDude** [comment]
28514be2c13660d27fff30bc187a63e6c024cd3b finally fixes this.

**Comment by tjvr** [comment]
I was getting this with the latest build from last night. Is that just me?

ie. when I place a block on top of snow, it moves up a block and the snow stays (as actown said)...

**Comment by mjevans** [comment]
Please re-open; this issue occurs again in the latest checkout ( ad04385d78efba77666db6134be7728b561da04f ) as of 2011-05-31.

**Comment by MostAwesomeDude** [comment]
Works for me. Do you have "build_snow" in your pre_build_hooks?

**Comment by MostAwesomeDude** [comment]
Closing. (Again.)
