### ISSUE TITLE
Torch Light

### ISSUE THREAD

**Issue by justinnoah** [bravoserver/bravo#71]
The client crashed when I was placing torches (not output from the log to say why), reconnected and found that the torches stopped lighting the area.

http://i.imgur.com/sGeCI.png

**Comment by MostAwesomeDude** [comment]
Does this crash still happen? I can't reproduce it.

**Comment by kingofkya** [comment]
I have a running server with this problem git update pulled feb 13  Go to server @ core.buizel.net  go inside the castle.

http://www.box.net/shared/5zfmnlggeu

**Comment by MostAwesomeDude** [comment]
Closing since I can't produce the crash.
