### ISSUE TITLE
Non-typical block attributes for plugins

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#72]
Shouldn't there be a centralized storage, like a database or meta file, to store information about blocks specific to plugins? Like if I had a portal plugin, It could use such storage to designate where portal blocks lead to. Also, other plugins, say, a kill block plugin, could overwrite this attribute or read it, to prevent complications.

**Comment by MostAwesomeDude** [comment]
This is plugin-specific and I think that plugins should generally be able to store this metadata themselves without any special complications.

**Comment by MostAwesomeDude** [comment]
Closing as something outside the scope of Bravo's beta stuff. (This would be a good thing for the IC conversation.)
