### ISSUE TITLE
Broken 2.5 compat.

### ISSUE THREAD

**Issue by actown** [bravoserver/bravo#77]
It looks like a recent commit has "import Functions" and this is not provided by python 2.5. http://www.everfall.com/paste/id.php?1vcqnsot2za1. Disreguard if this is fixed, it was brought up in the IRC channel.

**Comment by MostAwesomeDude** [comment]
fractions, not functions, I'd hope. The pastebin is expired, but I saw the discussion and fixed the offending code. Turns out it's simpler as floats anyway. (What was I thinking?)

**Comment by bitcraft** [comment]
yay.  i don't have to comment out that stuff in blocks anymore.
