### ISSUE TITLE
Sign update hook

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#80]
This would be _really_ useful for plugins that use signs, like a portal plugin. Else, plugin programmers will have to resort to some inefficient metadata checking loop, which might lead to errors

**Comment by MostAwesomeDude** [comment]
'k, we can do this now. What needs to go into the hook? Coords and text?

**Comment by Varriount** [comment]
Yep.. Playername possibly? Whatever is sent in the build hooks, minus the material, plus the text and player. (I might also suggest sign state, like wall sign and orientation, but that may be too much)

**Comment by MostAwesomeDude** [comment]
Well, presumably, you want the sign to already be built, right? So you don't need the build data, just the coordinates.

**Comment by Varriount** [comment]
I guess that would be fine.

**Comment by Varriount** [comment]
Er, has this been commited yet? I don't see it in iBravo..

**Comment by MostAwesomeDude** [comment]
https://github.com/MostAwesomeDude/bravo/tree/sign-hook has two commits, one for the interface and one for the loader. I've tested it and it certainly appears to work. Comments?

**Comment by Varriount** [comment]
So, that hook fires at both sign creation and upon editing.. How could a plugin tell if a sign was placed vs the sign being edited? In all other respects besides that one, it is fine.

**Comment by MostAwesomeDude** [comment]
How would a client edit a sign? Is there a trick to it that I'm not familiar with?

The distinction is pretty straightforward, though, and there's already an if/else nearby that could be used to provide that.

Edit: Made this change to the sign-hook branch.

**Comment by Varriount** [comment]
Now that the branch has been merged, I'm closing.
