### ISSUE TITLE
Players cannot see each other

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#81]
Players on the same server are unable to see each other.

**Comment by MostAwesomeDude** [comment]
I still have not found out _why_ this is. Does anybody have any idea?

**Comment by irufus** [comment]
Does this happen immediately or after a lengthy period of time?

**Comment by Varriount** [comment]
MostAwesomeDude: You have to hook up the player entities created when a user logs in to mimic the clients movements.

**Comment by YellowOnion** [comment]
I can see my friend, but he was at the bottom of the frozen sea when he should have been next to me

**Comment by MostAwesomeDude** [comment]
Fuck yes, finally fixed this.
