### ISSUE TITLE
Tile plugin problems

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#89]
As far as I can tell, the tile plugin is preventing the server from sending metadata ,or the confirmation packet needed by the client to confirm that the block exists. This is causing ladders to become invisible, and signs to disappear.

**Comment by MostAwesomeDude** [comment]
This sounds like a gross oversimplification. Are you saying that, with all other things equal, the Tile build hook is preventing signs and ladders from placing correctly?

**Comment by MostAwesomeDude** [comment]
Is this still a problem? Can we get some specific tests that would demonstrate the problem?

**Comment by MostAwesomeDude** [comment]
0ca5c554344f15f85d2925cfd6c888341687f213 explicitly tests that ladders may pass through the tile plugin unchanged. The problem, if it exists, lies elsewhere.
