### ISSUE TITLE
Ampoule doesn't work on Win32

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#94]
This is probably because of pywin32, but Bravo will hang on windows when a client connects and ampoule is enabled.

**Comment by justinnoah** [comment]
Disable ampoule if you're using windows.

**Comment by MostAwesomeDude** [comment]
If you can figure out why this is, I'd appreciate knowing. For now, I'm marking this as a feature, and adding a comment in bravo.ini.

God, I hate Windows.

**Comment by barsch** [comment]
I'll give it a try in my win machines - will report later back on this.

**Comment by barsch** [comment]
How do I actually know ampoule is working correctly?

I installed ampoule and dependencies (pyopenssl, pywin32), set 'ampoule = yes' in the bravo.ini file and restartet - stdout log didn't change at all. Connecting with client works. Importing of ampoule in python interpreter did work too.

**Comment by Varriount** [comment]
For me, after generating a few chunks, the client's movements would freeze, and no other clients would be able to connect

**Comment by barsch** [comment]
confirmed - ampoule processes spawn after a while - and a few minutes later client crashes - no log message at all

Maybe related: http://ython.wordpress.com/2009/07/25/tx-ampoule-on-win32/

**Comment by MostAwesomeDude** [comment]
Probably related, yes. Of the relevant Twisted bugs, Twisted #3931 is still open. I've just submitted a patch for this to them.

Looking over the relevant code, there's nowhere in our AMP code where we should be passing Unicode, but I'll make sure.

**Comment by Varriount** [comment]
Ok.. Now it the client just hangs when receiving the initial data when logging on. I think the process may be stuck in a loop somewhere. Can someone confirm the state of ampoule support on Linux? Things may have changed.

**Comment by Varriount** [comment]
Opening up in a new ticket with specific info

**Comment by squiddy** [comment]
Isn't this ticket appropriate? 

```
<squiddy> twisted\internet\_dumbwin32proc.py lines 129,130,131
<squiddy> the second argument to CreatePipe is the buffersize
<squiddy> 0 means system default. apparently that is not sufficient
```

If one significantly increases the value, like 33000*5, bravo and ampoule work together on windows xp, and probably other versions too.
