### ISSUE TITLE
Chunk Selection Error

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#95]
Every once in a while, when a player modifies a particular chunk, (Chunk -1,-1?) The will get disconnected with an error stating that "Couldn't select in chunk (-1, -1)!" . Besides this message, no errors are reported.

**Comment by Varriount** [comment]
Fixed in one of my pull requests

**Comment by justinnoah** [comment]
I wouldn't close an issue until it's actually been fixed in MAD's bravo...
